2023-01-09T05:30:36.454527974Z I0109 05:30:36.454440       1 adapter.go:114] successfully using in-cluster auth
2023-01-09T05:30:36.911988791Z I0109 05:30:36.911947       1 dynamic_cafile_content.go:157] "Starting controller" name="request-header::/etc/tls/private/requestheader-client-ca-file"
2023-01-09T05:30:36.912078980Z I0109 05:30:36.912050       1 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/tls/private/client-ca-file"
2023-01-09T05:30:36.912171752Z I0109 05:30:36.912154       1 dynamic_serving_content.go:132] "Starting controller" name="serving-cert::/etc/tls/private/tls.crt::/etc/tls/private/tls.key"
2023-01-09T05:30:36.912426625Z I0109 05:30:36.912411       1 secure_serving.go:210] Serving securely on [::]:6443
2023-01-09T05:30:36.912452602Z I0109 05:30:36.912441       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
2023-01-09T15:18:58.568586440Z http2: server connection error from 10.130.0.2:56740: connection error: PROTOCOL_ERROR
2023-01-09T15:18:58.568652614Z http2: server connection error from 10.130.0.2:56740: connection error: PROTOCOL_ERROR
